/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class WebSocketServer {
  constructor(port: number)
  start(): Promise<void>
  broadcast(message: string): Promise<void>
  getPort(): number
}
